services:

  web:
    image: python:3.10-slim
    container_name: demo_web
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements.txt && python app.py"
    ports:
      - "8000:8000"
    networks:
      - app_net
    depends_on:
      - redis
      - database
    env_file:
      - ./.env_file     

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_log:/var/log/redis
    networks:
      - app_net
    env_file:
      - ./.env_file     

  database:
    image: postgres:16
    container_name: demo_database
    env_file:
      - ./.env_file      
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net

volumes:
  redis_log:
  db_data:

networks:
  app_net:
    driver: bridge
